### ISSUE TITLE
关于TextViiew设置layout_top和layout_bottom后内容居中问题

### ISSUE THREAD

**Issue by xinyujauchou** [mmin18/FlexLayout#11]
TextViiew设置layout_top和layout_bottom后，设置gravity无法居中。
如：
`<TextView
        android:background="@color/color4"
        android:gravity="center"
        android:text="这是TextView"
        app:layout_height="this.width*0.2"a
        app:layout_centerY="50%"
        app:layout_left="20%"
        app:layout_centerX="50%"
        app:layout_right="90%"
        app:layout_bottom="prev.top"
        app:layout_top="view1.bottom"/>`
即：同时设置android：layout_height 和 :layout_bottom、layout_top
       实际显示高度按app:layout_bottom、app:layout_top显示，但是内部居中是按android:layout_height显示
       除非删除android:layout_height 才正常显示

**Comment by mmin18** [comment]
为什么要同时设置top, bottom, height？

**Comment by mmin18** [comment]
upgrade to v1.2.5 (check code on dev branch)
