### ISSUE TITLE
Docs: Clarify prev/next Meaning

### ISSUE THREAD

**Issue by commonsguy** [mmin18/FlexLayout#2]
> Reference previous view using `prev`, next view using `next`

"Previous" and "next" in terms of... what?
- Position in the XML layout file?
- Location with respect to the property? (e.g., for `app:layout_left="prev.right"`, `prev` means "whatever's closest to us on the left")
- Something else?

The rest of the rules seem straight-forward, but IMHO this description could use a bit more love.

Thanks!

**Comment by xu6148152** [comment]
Great suggestion!

**Comment by mmin18** [comment]
Great suggestion, Thanks!
