### ISSUE TITLE
Could it possible to support max_width/max_height/min_width/min_height ?

### ISSUE THREAD

**Issue by Piasy** [mmin18/FlexLayout#5]

**Comment by mmin18** [comment]
Could you use android:minWidth, android:maxWidth?

**Comment by Piasy** [comment]
I can, but they are far less powerful :(

For example, I have a single line TextView, it need a drawable at its right, the TextView's width should be wrap_content (to let the drawable stay together with text), but should have a max width. I hope I can set its max width according to parent width, to let it expand as wide as possible. 

I have to set max width in Java code.

**Comment by mmin18** [comment]
I see. There is two ways to express: app:layout_width="max(wrap_content, 100%-this.left-icon.left)" or I can add 4 new params app:layout_minWidth ...
The first one is more universal and flexible, and the second one is more easy to understand. Which one do you prefer?

**Comment by Piasy** [comment]
Great! First one is awesome enough, it shows the power of FlexLayout again! 

A little suggestion, that usage could be added into documentation :)

**Comment by Piasy** [comment]
But it seems FlexLayout doesn't support `wrap_content` inside `max` function? I use `1.2.2`, the IDE preview gives an error:

``` java
java.lang.IllegalArgumentException: unknown token wrap_content, layout_width=max(wrap_content, 100% - this.left - icon.left)
```

Is it just a IDE preview bug?

**Comment by mmin18** [comment]
No I haven't implemented it yet.

**Comment by Piasy** [comment]
Got it.

**Comment by mmin18** [comment]
Check https://github.com/mmin18/FlexLayout/tree/dev (upgrade to v1.2.3)
