### ISSUE TITLE
Always true conditions

### ISSUE THREAD

**Issue by ozodrukh** [mmin18/FlexLayout#6]
<img width="460" alt="screen shot 2016-04-24 at 12 07 04 pm" src="https://cloud.githubusercontent.com/assets/3184950/14766038/257f7958-0a15-11e6-98f0-7bc3ce60df23.png">

Hmm... conditions like this are always true, is it for testing purpose or what?

**Comment by mmin18** [comment]
Float.NaN == Float.NaN always return false.

**Comment by ozodrukh** [comment]
May be better to use Float.isNaN() or Double.isNaN()
